//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiveria.Home.Modbus.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tiveria.Home.Modbus.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The quantity must not be higher than {0}. ähnelt.
        /// </summary>
        internal static string Ex_ArgumentOutOfRange_QuantityHigherThan {
            get {
                return ResourceManager.GetString("Ex_ArgumentOutOfRange_QuantityHigherThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server accepted the service invocation but requires more time to execute it and therefore only sent an acknowledgement. ähnelt.
        /// </summary>
        internal static string Protocol_Acknowledge {
            get {
                return ResourceManager.GetString("Protocol_Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The gateway path is not available. ähnelt.
        /// </summary>
        internal static string Protocol_GatewayPathUnavailable {
            get {
                return ResourceManager.GetString("Protocol_GatewayPathUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The targeted device failed to respond. Exception generated by gateway. ähnelt.
        /// </summary>
        internal static string Protocol_GatewayTargetDeviceFailedToRespond {
            get {
                return ResourceManager.GetString("Protocol_GatewayTargetDeviceFailedToRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data address received is not allowed for the requested function. ähnelt.
        /// </summary>
        internal static string Protocol_IllegalDataAddress {
            get {
                return ResourceManager.GetString("Protocol_IllegalDataAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A value provided in the query data is not allowed in the context of the requested function. ähnelt.
        /// </summary>
        internal static string Protocol_IllegalDataValue {
            get {
                return ResourceManager.GetString("Protocol_IllegalDataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The function code is unknown by the server. ähnelt.
        /// </summary>
        internal static string Protocol_IllegalFunction {
            get {
                return ResourceManager.GetString("Protocol_IllegalFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The protocol id received is not following the standard. 0x00 was expected. ähnelt.
        /// </summary>
        internal static string Protocol_IllegalProtocolId {
            get {
                return ResourceManager.GetString("Protocol_IllegalProtocolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The received transactionId is not matching the sent one. ähnelt.
        /// </summary>
        internal static string Protocol_IllegalTransactionId {
            get {
                return ResourceManager.GetString("Protocol_IllegalTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The received unitId is not matching the sent one. ähnelt.
        /// </summary>
        internal static string Protocol_IllegalUnitId {
            get {
                return ResourceManager.GetString("Protocol_IllegalUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server was unable to handle the request as it is busy. ähnelt.
        /// </summary>
        internal static string Protocol_ServerBusy {
            get {
                return ResourceManager.GetString("Protocol_ServerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server failed during execution of the request. ähnelt.
        /// </summary>
        internal static string Protocol_ServerFailure {
            get {
                return ResourceManager.GetString("Protocol_ServerFailure", resourceCulture);
            }
        }
    }
}
